spring.application.name=gamesbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/gamesdb
spring.datasource.username=gamesUser
spring.datasource.password=gamesPW

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
